---
  - hosts: control
    become: true	#give sudo privilege
    tasks:
      - name: Install common tools on the master
        apt: >
             name={{item}} 
             state=present
             update_cache=yes
        with_items:
          - curl
          - wget
          - vim
          - tree
          - git 
