---
  - hosts: webservers
    become: true	#give sudo privilege
    tasks:
      - name: Install apache 2 webserver >
        apt: >
             name=apache2
             state=present
             update_cache=yes

      - service: name=apache2 state=started enabled=yes

          
