FROM nginx:alpine
MAINTAINER Moti Abudi


#Override the default tomcat conf files and set user credtials and allow managing from any host
COPY conf/nginx.conf /etc/nginx/nginx.conf
#COPY conf/sites-available/default /etc/nginx/conf/site-available/default

#EXPOSE 8080
#EXPOSE 80
#EXPOSE 443

